- name: Install MySQL
  hosts: mysqlserver
  remote_user: azureuser
  become: true
  become_user: root
  vars:
    MySQL_root_pass: ReplaceWithYourPassword

  tasks:
    - name: Install MySQL packages
      apt:
        name: "{{ item }}"
        state: present
        force: yes
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      with_items:
        - mysql-server
        - mysql-client
