# webrole/tasks/main.yml

- name: "Installer le package du serveur web"
  package:
    name: "apache2"
    state: present

- name: "Copier la page web"
  copy:
    content: "Le TP était facile, ça mérite un 20/20 {{ ansible_nodename }}"
    dest: "/var/www/html/index.html"

- name: "Démarrer le service du serveur web"
  service:
    name: "apache2"
    state: started
